### ISSUE TITLE
request: Docker version

### ISSUE THREAD

**Issue by iFloris** [zhoubear/open-paperless#1]
Hello, your tool looks really interesting.
Would it be possible to have an Docker version so that people can test it quickly and effortlessly?

**Comment by ytjohn** [comment]
open-paperless is a cash grab, no attribution fork of Mayan EDMS.  Fortunately, Mayan EDMS has a really nice [Docker image](https://gitlab.com/mayan-edms/mayan-edms-docker).

**Comment by iFloris** [comment]
Thanks for the heads up @ytjohn, I just noticed the reddit thread discussion as well. Shame that this happens, but looking at that really nice Docker image from Mayan EDMS!
