### ISSUE TITLE
Travis testing is not yet turned on for this repo

### ISSUE THREAD

**Issue by cclauss** [zhoubear/open-paperless#11]
Travis testing is free for open source projects like this one.  Turning it on would require going to https://travis-ci.org/profile/zhoubear and logging in with Github credentials and then switching the toggle for this repo to the __on__ position.  This is a great way to find bugs before your users do.

**Comment by zhoubear** [comment]
Done! Thanks!
https://travis-ci.org/zhoubear/open-paperless/builds/320339627
