### ISSUE TITLE
Running on localhost

### ISSUE THREAD

**Issue by rajksbth** [zhoubear/open-paperless#12]
After  installation its running on localhost.
How to run on '0.0.0.0:8000'

**Comment by zhoubear** [comment]
Looking at the gunicorn documentation to find out.

**Comment by scriptingislife** [comment]
In `circus.ini` I added `-b 0.0.0.0:8000` to the cmd argument. This specifies where to bind to.

**Comment by zhoubear** [comment]
Added @becksteadn solution here https://github.com/zhoubear/open-paperless/commit/6b9ed1f21908116ad2795b3785b2dbd66713d66e

**Comment by rajksbth** [comment]
Thanks for your prompt response!
