### ISSUE TITLE
Project Discontinued?

### ISSUE THREAD

**Issue by ndbeals** [zhoubear/open-paperless#21]
Hello, 

I recently stumbled across this and would like to use it, but don't really want to start using software that's EOL before I even started.

So, is this project dead?

**Comment by Homy1** [comment]
Yes, I have the same question.

It would be good if someone can answer this question or fix the issues.

**Comment by tooomm** [comment]
The screenshots are looking pretty cool, also just discovered this...

**Comment by oscardobsonbrown** [comment]
According to openpaperless.com
"October 3, 2018 - Open Paperless has been acquired by Mayan EDMS! We are thrilled to be now part of the project upon which we built ours.

**Comment by SalahAdDin** [comment]
what does it mean?

**Comment by julianfoad** [comment]
According to Mayan EDMS https://www.mayan-edms.com/ they appear to have moved the source code to GitLab (hurray!):
https://gitlab.com/mayan-edms/mayan-edms
